{% set data = load_setup_py_data() %}

package:
  name: q2-emperor
  version: {{ data.get('version') }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools
    - numpy
    - pandas
    - scikit-bio
    - emperor
    - qiime2 2017.3.*
    - q2templates 2017.3.*
    - q2-types 2017.3.*

  run:
    - python 3.5*
    - setuptools
    - numpy
    - pandas
    - scikit-bio
    - emperor
    - qiime2 2017.3.*
    - q2templates 2017.3.*
    - q2-types 2017.3.*

test:
  imports:
    - q2_emperor
    - qiime2.plugins.emperor

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
