{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-emperor
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - numpy
    - pandas
    - scikit-bio
    - emperor 1.0.0beta8
    - qiime2 {{ release }}.*
    - q2templates {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_emperor
    - qiime2.plugins.emperor

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
