{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-emperor
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - numpy
    - pandas {{ pandas }}
    - scikit-bio {{ scikit_bio }}
    - emperor ==1.0.3
    - qiime2 {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2templates >={{ q2templates }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_emperor
    - qiime2.plugins.emperor

  commands:
    - py.test --pyargs q2_emperor

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
